'use client'
import { Shell, usePortal, money } from '@/components/Page'
export default function POs() {
  const { data, err, loading } = usePortal('po-history')
  return (
    <Shell title="Purchase Orders">
      {loading && <p className="muted">Loading…</p>}{err && <div className="err">{err}</div>}
      {data && (
        <div className="panel"><h3>PO history (generated by admin)</h3>
          <table className="ptable"><thead><tr><th>PO No</th><th>Date</th><th>Site</th><th>Value</th><th>Paid</th><th>Outstanding</th><th>Delivery</th><th>Status</th></tr></thead>
          <tbody>{(data.purchase_orders || []).length === 0 && <tr><td colSpan={8} style={{ textAlign:'center', color:'#6b7a90', padding:20 }}>No purchase orders.</td></tr>}
          {(data.purchase_orders || []).map(p => (<tr key={p.id}><td><strong>{p.po_number}</strong></td><td>{p.po_date}</td><td>{p.project_site_name}</td>
            <td>₹{money(p.total_po_value)}</td><td>₹{money(p.paid_amount)}</td><td>₹{money(p.outstanding_amount)}</td>
            <td><span className="pill">{(p.delivery_status||'').replace('_',' ')}</span></td><td><span className="pill">{(p.status||'').replace('_',' ')}</span></td></tr>))}
          </tbody></table></div>
      )}
    </Shell>
  )
}
